eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    health-check-url-path: /health
    metadata-map:
      instance-id: test-sidecar
      management:
        context-path: ${management.context-path}
      user:
        name: test
        password: test
    prefer-ip-address: true
    status-page-url-path: /info
management:
  context-path: /admin
server:
  port: 0
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true
    mime-types: text/html, text/xml, text/plain, text/css, application/json, application/xml
spring:
  application:
    name: test-boot-issue
